Lab-3
georgedem975/web pull request #4
Opened 2023-09-18 21:33 UTC by georgedem975

2023-10-07 12:15 UTC, Artttdez requested changes

2023-10-07 12:15 UTC, Artttdez commented on styles.css
> +    position: absolute;
не понял, зачем тут абсолютное позиционирование. Хочется, чтобы ты его применил осмысленно. Например, изменить положение абсолютного блога относительно родителя с position:relative, отцентровать его, или еще как то

2023-10-17 22:50 UTC, georgedem975 commented on styles.css
> +    position: absolute;
только из-за того что просили в задании, просто не знал куда его пихнуть так чтобы от его использования был смысл, по крайней мере на данный момент не вижу смысла в его использовании

2023-10-21 12:34 UTC, Artttdez requested changes
Вижу работу с grid, @media, не нашел абсолютного позиционирования. Придумай какой то элемент, для которого это будет нужно и примени

2023-10-28 11:35 UTC, Artttdez approved these changes
Вижу абсолютное позиционирование, лабу принимаю)

2023-11-26 15:40 UTC, merged