Lab 7
georgedem975/web pull request #9
Opened 2023-12-09 11:56 UTC by georgedem975

2023-12-12 20:24 UTC, Artttdez requested changes
<img width="366" alt="image" src="https://github.com/georgedem975/web/assets/63268862/141fe454-5d46-4ec2-bf65-2a430c19a013">
Локально запустил, переменная anime, с которой похоже должна была быть работа, не объявлена. Посмотри пожалуйста что не так

2023-12-16 12:13 UTC, georgedem975 commented
сделал прелоадер с помощью animejs

2023-12-16 13:06 UTC, Artttdez requested changes
6 - ок. 

7 - не понял смысла втянутой библиотеки)) Опиши юз-кейс, зачем тебе эти крутящиеся квадратики. Можно сделать так - что типа так у тебя отображается 3д моделька например, а не просто что то вертится внизу страницы

2023-12-16 13:32 UTC, georgedem975 commented
я же выше написал что прелоадер с анимацией

2023-12-16 13:40 UTC, Artttdez approved these changes
7 тоже done

2023-12-16 13:49 UTC, merged